/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as SharesIndexRouteImport } from './routes/shares/index'
import { Route as ProvidersIndexRouteImport } from './routes/providers/index'
import { Route as LibraryIndexRouteImport } from './routes/library/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PlaylistsPlaylistIdRouteImport } from './routes/playlists/$playlistId'
import { Route as ArtistsArtistIdRouteImport } from './routes/artists/$artistId'
import { Route as AlbumsAlbumIdRouteImport } from './routes/albums/$albumId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminProvidersRouteImport } from './routes/admin/providers'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesIndexRoute = SharesIndexRouteImport.update({
  id: '/shares/',
  path: '/shares/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIndexRoute = ProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryIndexRoute = LibraryIndexRouteImport.update({
  id: '/library/',
  path: '/library/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsPlaylistIdRoute = PlaylistsPlaylistIdRouteImport.update({
  id: '/playlists/$playlistId',
  path: '/playlists/$playlistId',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsArtistIdRoute = ArtistsArtistIdRouteImport.update({
  id: '/artists/$artistId',
  path: '/artists/$artistId',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumsAlbumIdRoute = AlbumsAlbumIdRouteImport.update({
  id: '/albums/$albumId',
  path: '/albums/$albumId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProvidersRoute = AdminProvidersRouteImport.update({
  id: '/admin/providers',
  path: '/admin/providers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/admin': typeof AdminIndexRoute
  '/history': typeof HistoryIndexRoute
  '/library': typeof LibraryIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/shares': typeof SharesIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/admin': typeof AdminIndexRoute
  '/history': typeof HistoryIndexRoute
  '/library': typeof LibraryIndexRoute
  '/providers': typeof ProvidersIndexRoute
  '/shares': typeof SharesIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/admin/providers': typeof AdminProvidersRoute
  '/admin/users': typeof AdminUsersRoute
  '/albums/$albumId': typeof AlbumsAlbumIdRoute
  '/artists/$artistId': typeof ArtistsArtistIdRoute
  '/playlists/$playlistId': typeof PlaylistsPlaylistIdRoute
  '/admin/': typeof AdminIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/library/': typeof LibraryIndexRoute
  '/providers/': typeof ProvidersIndexRoute
  '/shares/': typeof SharesIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/admin/providers'
    | '/admin/users'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/admin'
    | '/history'
    | '/library'
    | '/providers'
    | '/shares'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/admin/providers'
    | '/admin/users'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/admin'
    | '/history'
    | '/library'
    | '/providers'
    | '/shares'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/onboarding'
    | '/profile'
    | '/register'
    | '/reset-password'
    | '/setup'
    | '/admin/providers'
    | '/admin/users'
    | '/albums/$albumId'
    | '/artists/$artistId'
    | '/playlists/$playlistId'
    | '/admin/'
    | '/history/'
    | '/library/'
    | '/providers/'
    | '/shares/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  AdminProvidersRoute: typeof AdminProvidersRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AlbumsAlbumIdRoute: typeof AlbumsAlbumIdRoute
  ArtistsArtistIdRoute: typeof ArtistsArtistIdRoute
  PlaylistsPlaylistIdRoute: typeof PlaylistsPlaylistIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  LibraryIndexRoute: typeof LibraryIndexRoute
  ProvidersIndexRoute: typeof ProvidersIndexRoute
  SharesIndexRoute: typeof SharesIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares/': {
      id: '/shares/'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof SharesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/': {
      id: '/providers/'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/': {
      id: '/library/'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$playlistId': {
      id: '/playlists/$playlistId'
      path: '/playlists/$playlistId'
      fullPath: '/playlists/$playlistId'
      preLoaderRoute: typeof PlaylistsPlaylistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/$artistId': {
      id: '/artists/$artistId'
      path: '/artists/$artistId'
      fullPath: '/artists/$artistId'
      preLoaderRoute: typeof ArtistsArtistIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/albums/$albumId': {
      id: '/albums/$albumId'
      path: '/albums/$albumId'
      fullPath: '/albums/$albumId'
      preLoaderRoute: typeof AlbumsAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/providers': {
      id: '/admin/providers'
      path: '/admin/providers'
      fullPath: '/admin/providers'
      preLoaderRoute: typeof AdminProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  AdminProvidersRoute: AdminProvidersRoute,
  AdminUsersRoute: AdminUsersRoute,
  AlbumsAlbumIdRoute: AlbumsAlbumIdRoute,
  ArtistsArtistIdRoute: ArtistsArtistIdRoute,
  PlaylistsPlaylistIdRoute: PlaylistsPlaylistIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  LibraryIndexRoute: LibraryIndexRoute,
  ProvidersIndexRoute: ProvidersIndexRoute,
  SharesIndexRoute: SharesIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
