import { unlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import type { ILogger } from './logger';

export async function generateCookiesFile(domain: string, cookieHeader: string): Promise<string> {
  if (!cookieHeader || cookieHeader === 'undefined') {
    throw new Error('Invalid cookie header: cookies are required and cannot be undefined');
  }
  const cookieDomain = domain.startsWith('.') ? domain : `.${domain}`;
  const expiration = Math.floor(Date.now() / 1000) + 86400 * 365;
  const cookiePairs = cookieHeader
    .split(';')
    .map((p) => p.trim())
    .filter((p) => p.includes('='));
  const cookieLines = cookiePairs.map((pair) => {
    const [name, ...valueParts] = pair.split('=');
    const value = valueParts.join('=');
    const isSecure = name?.startsWith('__Secure-') || name?.startsWith('__Host-');
    return `${cookieDomain}\tTRUE\t/\t${isSecure ? 'TRUE' : 'FALSE'}\t${expiration}\t${name}\t${value || ''}`;
  });
  const cookiesContent = ['# Netscape HTTP Cookie File', '# This file is generated by yt-dlp. Do not edit.', '', ...cookieLines].join('\n');
  const tempPath = join(tmpdir(), `cookies-${domain.replace(/\./g, '-')}-${Date.now()}.txt`);
  await writeFile(tempPath, cookiesContent, 'utf-8');
  return tempPath;
}

export async function deleteCookiesFile(cookiesPath: string, logger?: ILogger): Promise<void> {
  try {
    await unlink(cookiesPath);
  } catch (error) {
    if (logger) logger.warn(`Failed to delete temporary cookies file: ${cookiesPath}`, error);
    else console.warn(`Failed to delete temporary cookies file: ${cookiesPath}`, error);
  }
}

export function parseCookies(content: string): string {
  const cookies: string[] = [];
  for (const line of content.split('\n')) {
    if (line.startsWith('#') || line.trim() === '') continue;
    const parts = line.split('\t');
    if (parts.length >= 7 && parts[5] && parts[6]) {
      const name = parts[5].trim();
      const value = parts[6].trim();
      if (name && value) cookies.push(`${name}=${value}`);
    }
  }
  return cookies.join('; ');
}
