/// <reference path="../pb_data/types.d.ts" />
migrate((app) => {
  const collection = new Collection({
    createRule: '',
    deleteRule: '',
    fields: [
      {
        autogeneratePattern: '[a-z0-9]{15}',
        hidden: false,
        id: 'text3208210256',
        max: 15,
        min: 15,
        name: 'id',
        pattern: '^[a-z0-9]+$',
        presentable: false,
        primaryKey: true,
        required: true,
        system: true,
        type: 'text',
      },
      {
        autogeneratePattern: '',
        hidden: false,
        id: 'text1579384326',
        max: 0,
        min: 0,
        name: 'name',
        pattern: '',
        presentable: false,
        primaryKey: false,
        required: true,
        system: false,
        type: 'text',
      },
      {
        autogeneratePattern: '',
        hidden: false,
        id: 'text2063623452',
        max: 0,
        min: 0,
        name: 'description',
        pattern: '',
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: 'text',
      },
      {
        hidden: false,
        id: 'file2366146245',
        maxSelect: 1,
        maxSize: 0,
        mimeTypes: [
          'image/jpeg',
          'image/png',
          'image/svg+xml',
          'image/gif',
          'image/webp',
        ],
        name: 'cover',
        presentable: false,
        protected: false,
        required: false,
        system: false,
        thumbs: [],
        type: 'file',
      },
      {
        autogeneratePattern: '',
        hidden: false,
        id: 'text3875796498',
        max: 0,
        min: 0,
        name: 'coverUrl',
        pattern: '',
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: 'text',
      },
      {
        autogeneratePattern: '',
        hidden: false,
        id: 'text4129894498',
        max: 0,
        min: 0,
        name: 'sourceUrl',
        pattern: '',
        presentable: false,
        primaryKey: false,
        required: false,
        system: false,
        type: 'text',
      },
      {
        cascadeDelete: false,
        collectionId: 'pbc_327047008',
        hidden: false,
        id: 'relation3479234172',
        maxSelect: 9999,
        minSelect: 0,
        name: 'tracks',
        presentable: false,
        required: false,
        system: false,
        type: 'relation',
      },
      {
        cascadeDelete: false,
        collectionId: '_pb_users_auth_',
        hidden: false,
        id: 'relation4154657856',
        maxSelect: 1,
        minSelect: 0,
        name: 'user',
        presentable: false,
        required: true,
        system: false,
        type: 'relation',
      },
      {
        hidden: false,
        id: 'autodate2990389176',
        name: 'created',
        onCreate: true,
        onUpdate: false,
        presentable: false,
        system: false,
        type: 'autodate',
      },
      {
        hidden: false,
        id: 'autodate3332085495',
        name: 'updated',
        onCreate: true,
        onUpdate: true,
        presentable: false,
        system: false,
        type: 'autodate',
      },
    ],
    id: 'pbc_playlists',
    indexes: [],
    listRule: '',
    name: 'playlists',
    system: false,
    type: 'base',
    updateRule: '',
    viewRule: '',
  });

  return app.save(collection);
}, (app) => {
  const collection = app.findCollectionByNameOrId('pbc_playlists');
  return app.delete(collection);
});
